version: "3.8"

services:
  app:
    build: .
    container_name: labobackend_app
    volumes:
      - .:/var/www
    ports:
      - "9001:9000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: labo2
      DB_USERNAME: Ramaseck
      DB_PASSWORD: maraseck
    command: >
      sh -c "composer install && php artisan migrate --force && php-fpm"

  db:
    image: mysql:8
    container_name: labobackend_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: labo2
      MYSQL_USER: Ramaseck
      MYSQL_PASSWORD: maraseck
     
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
